language: node_js
node_js: node
jobs:
  include:
  - stage: test
    name: "Jest"
    script: npm test
  - name: "Lint"
    install: npm install standard
    script: npm run lint
  - stage: deploy
    name: "Deploy"
    if: tag IS present
    script: skip
    deploy:
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_API_KEY
      on:
        tags: true